### PR TITLE
Drop support for ruby 2.2

### PR DESCRIPTION
**Pull request by nijikon**
Support for ruby 2.2 ended on March 31, 2018.

https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

### CODE REVIEW

**Comment by mastahyeti** [comment]
Is the main argument for dropping support for 2.2 that we can remove the explicit `String#freeze` calls, or is the goal just to stay updated with support for the language?

**Comment by nijikon** [comment]
I would say both, plus we should not encourage people to run outdated ruby versions. They will still be able to run the last version that supports 2.2 if needed.

**Comment by mastahyeti** [comment]
My inclination would be to not remove support for old Ruby versions without a compelling reason. I, for example, wouldn't want to force someone running Ruby 2.2 to update their Ruby version before being able to update this library for a security fix. People _should_ be running supported versions of Ruby, but I don't think it's this library's job to convince them of that.

**Comment by nijikon** [comment]
We won't force anybody to upgrade, that's not my intention here. We can do a major bump after dropping support and if anything needs to be backported it can.

**Comment by nijikon** [comment]
Bumping this again, I still think that we should drop support for version `< 2.3`, recently `bundler` did that and community is following that trend. People can always use the older version which supports `2.2` version.

**Comment by nijikon** [comment]
@mastahyeti ping

**Comment by mastahyeti** [comment]
I still don't see the benefit of removing support for older versions of Ruby. Maybe if there was a lot of active development on the repository and missing language features were a major annoyance to contributors. But, the U2F protocol itself is deprecated and I don't foresee a lot of activity on this repository moving forward. Removing support for old Ruby versions just for the sake of doing it doesn't seem compelling to me. This isn't my repo though and the @castle folks might feel differently.

**Comment by nijikon** [comment]
People can always disagree and it's fine. I'm part of @castle team and we will be dropping support for 2.2 as we want to have this repository up-to-date.

**Pull request merged**
