### PR TITLE
Add missing version field to FakeU2F#register_response

### PR DESCRIPTION
**Pull request by mastahyeti**
[Here's](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-javascript-api-v1.2-ps-20170411.html#dictionary-registerresponse-members) the relevant section of the spec.

### CODE REVIEW

**Comment by mastahyeti** [comment]
I'm seeing errors in TravisCI build output about Coditsu being misconfigured. Not sure what's up with that.

**Comment by nijikon** [comment]
@mastahyeti sorry for that. I fixed everything in `master`, you should be good after you rebase.

**Comment by mastahyeti** [comment]
Thanks @nijikon!

**Comment by nijikon** [comment]
OK, it does not work, I can look into that tomorrow morning, hope that works for you.

**Pull request closed without merging**
