### PR TITLE
Add validation to load_from_json methods

### PR DESCRIPTION
**Pull request by go2sh**
Hi,

I added validation to the load_from_json methods. I check for for a string-like object and catch the JSON::ParserError for invalid format. Afterwards a ClientDataTypeError exceptions gets thrown.
Test are also included.

Chris

### CODE REVIEW

**Comment by wallin** [comment]
Thanks! Does `JSON.parse` automatically call `to_s` before parsing or do we need to to that before calling it?

**Comment by go2sh** [comment]
I'm not sure. I don't know if ruby's C-Interface converts objects to strings. We can either do it or we can use the load method, which uses to_s. ( Basically a wrapper around parse )
http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html

**Comment by wallin** [comment]
Right. I'm a bit hesitant to using `load` because of the Warning issued in the docs:
http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html#method-i-load
The JSON could definitely be untrusted.

Another option could be to be more strict and just check it the input `is_a? String`. What do you think?

**Comment by go2sh** [comment]
I tried that, since you use ``` param['response'] ``` the object isn't a string. By the way, it means, that parse convert it to a string. So I think i should be fine to test for to_s and then actually call ``` JSON::parse(json.to_s) ``` to be sure. One thing about load. It also uses the parse function, which then uses the cParser. In general you have to trust in the cParser to be error free.

But thats only the parser, I think, we need to check more:
- [ ] Check if the two fields exist in the data object
- [ ] Check if they contain correct data, so that byteslice dosen't fail

**Comment by wallin** [comment]
Yes you're right, that makes sense. Thanks for fixing this!

**Comment by wallin** [comment]
Hey, any updates on this? Anything I can do to help?

**Pull request closed without merging**
